/*
 * CSCI 469
 * Project #1
 * Tan, Josh
 * 10/08/13
 */
package caesarcipher;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 * The GUI frame used to demonstrate the cipher. Allows the user to specify the
 * shift size and plaintext, and provides the resulting ciphertext. The
 * ciphertext is shown immediately as the user makes changes the plaintext or
 * shift setting.
 *
 * @author Josh Tan
 */
public class CipherFrame extends javax.swing.JFrame {

    private Cipher caesarCipher; // cipher used for encryption

    /**
     * Creates new form CipherFrame
     */
    public CipherFrame() {
        initComponents();

        // whenever the user removes, inserts, and changes the plaintext,
        // recompute and display the corresponding ciphertext
        plainArea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void removeUpdate(DocumentEvent e) {
//                cipherArea.setText(caesarCipher.encipher(plainArea.getText()));
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
//                cipherArea.setText(caesarCipher.encipher(plainArea.getText()));
            }

            @Override
            public void changedUpdate(DocumentEvent arg0) {
//                cipherArea.setText(caesarCipher.encipher(plainArea.getText()));
            }
        });

        // initialize the cipher with the appropriate shift setting
        caesarCipher = new Cipher((Integer) shiftSpinner.getValue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caesarPanel = new javax.swing.JPanel();
        shiftLabel = new javax.swing.JLabel();
        shiftSpinner = new javax.swing.JSpinner();
        caesarTitle = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cipherPanel = new javax.swing.JPanel();
        cipherScrollPane = new javax.swing.JScrollPane();
        cipherArea = new javax.swing.JTextArea();
        plainPanel = new javax.swing.JPanel();
        plainScrollPane = new javax.swing.JScrollPane();
        plainArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cipherPanel1 = new javax.swing.JPanel();
        cipherScrollPane1 = new javax.swing.JScrollPane();
        cipherArea1 = new javax.swing.JTextArea();
        plainPanel3 = new javax.swing.JPanel();
        plainScrollPane3 = new javax.swing.JScrollPane();
        plainArea3 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("caesarFrame"); // NOI18N

        shiftLabel.setText("Cipher Shift:");

        shiftSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 127, 1));
        shiftSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinUpdater(evt);
            }
        });

        caesarTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        caesarTitle.setText("A Simple Caesar Cipher");

        jTabbedPane2.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("TabbedPane.selected"), 1, true));
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(501, 507));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cipherPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ciphertext"));
        cipherPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cipherArea.setEditable(false);
        cipherArea.setColumns(20);
        cipherArea.setLineWrap(true);
        cipherArea.setRows(5);
        cipherArea.setWrapStyleWord(true);
        cipherScrollPane.setViewportView(cipherArea);

        cipherPanel.add(cipherScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 450, 130));

        jPanel1.add(cipherPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 470, 160));

        plainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Plaintext"));
        plainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plainArea.setColumns(20);
        plainArea.setLineWrap(true);
        plainArea.setRows(5);
        plainArea.setWrapStyleWord(true);
        plainArea.setName(""); // NOI18N
        plainScrollPane.setViewportView(plainArea);

        plainPanel.add(plainScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 450, 130));

        jPanel1.add(plainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 470, 160));

        jButton1.setText("Encrypt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jTabbedPane2.addTab("Encryption", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cipherPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ciphertext"));
        cipherPanel1.setPreferredSize(new java.awt.Dimension(470, 155));
        cipherPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cipherArea1.setColumns(20);
        cipherArea1.setLineWrap(true);
        cipherArea1.setRows(5);
        cipherArea1.setWrapStyleWord(true);
        cipherArea1.setMinimumSize(new java.awt.Dimension(100, 15));
        cipherArea1.setName(""); // NOI18N
        cipherScrollPane1.setViewportView(cipherArea1);

        cipherPanel1.add(cipherScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 450, 130));

        jPanel2.add(cipherPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, 160));

        plainPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Plaintext"));
        plainPanel3.setPreferredSize(new java.awt.Dimension(470, 163));
        plainPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plainArea3.setEditable(false);
        plainArea3.setColumns(20);
        plainArea3.setLineWrap(true);
        plainArea3.setRows(5);
        plainArea3.setWrapStyleWord(true);
        plainArea3.setName(""); // NOI18N
        plainScrollPane3.setViewportView(plainArea3);

        plainPanel3.add(plainScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 450, 130));

        jPanel2.add(plainPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 160));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jButton4.setText("Decrypt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jTabbedPane2.addTab("Decryption", jPanel2);

        javax.swing.GroupLayout caesarPanelLayout = new javax.swing.GroupLayout(caesarPanel);
        caesarPanel.setLayout(caesarPanelLayout);
        caesarPanelLayout.setHorizontalGroup(
            caesarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caesarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(caesarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caesarTitle)
                    .addGroup(caesarPanelLayout.createSequentialGroup()
                        .addComponent(shiftLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shiftSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        caesarPanelLayout.setVerticalGroup(
            caesarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caesarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(caesarTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(caesarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shiftLabel)
                    .addComponent(shiftSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setMnemonic('F');
        jMenu1.setText("File");

        jMenuItem1.setMnemonic('x');
        jMenuItem1.setText("Exit");
        jMenuItem1.setToolTipText("Exit Application");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(caesarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(caesarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinUpdater(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinUpdater
//        caesarCipher.setShift((Integer) shiftSpinner.getValue());
//        cipherArea.setText(caesarCipher.encipher(plainArea.getText()));
    }//GEN-LAST:event_spinUpdater

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int shift = (Integer) shiftSpinner.getValue();
        String plainText = plainArea.getText();
        caesarCipher.setShift(shift);
        cipherArea.setText(caesarCipher.encipher(plainText));        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        plainArea.setText("");
        cipherArea.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int shift = (Integer) shiftSpinner.getValue();
        String cipherText = cipherArea1.getText();
        caesarCipher.setShift(shift);
        plainArea3.setText(caesarCipher.decipher(cipherText));        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        plainArea3.setText("");
        cipherArea1.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
//                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CipherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CipherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CipherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CipherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                CipherFrame cipherFrame = new CipherFrame();
                cipherFrame.setTitle("Caesar Cipher");
                cipherFrame.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel caesarPanel;
    private javax.swing.JLabel caesarTitle;
    private javax.swing.JTextArea cipherArea;
    private javax.swing.JTextArea cipherArea1;
    private javax.swing.JPanel cipherPanel;
    private javax.swing.JPanel cipherPanel1;
    private javax.swing.JScrollPane cipherScrollPane;
    private javax.swing.JScrollPane cipherScrollPane1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea plainArea;
    private javax.swing.JTextArea plainArea3;
    private javax.swing.JPanel plainPanel;
    private javax.swing.JPanel plainPanel3;
    private javax.swing.JScrollPane plainScrollPane;
    private javax.swing.JScrollPane plainScrollPane3;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JSpinner shiftSpinner;
    // End of variables declaration//GEN-END:variables
}
